[package]
name = "ape"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
creak = "0.3.0"
realfft = "3.1.0"
rustfft = "6.1.0"
itertools = "0.10.5"
